services:
  chatbot:    
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: streamlit_chatbot
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    # Optional : live reload app changes without rebuilding image
    volumes:
      - ../app:/app/app